### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by Z-fly** [Bronya0/ES-King#2]
![image](https://github.com/Bronya0/ES-King/assets/10470892/e7f8587b-a685-4654-83c8-3544f3d4affc)
![image](https://github.com/Bronya0/ES-King/assets/10470892/d45c3371-a8f2-427f-b6ea-ad9548fe073c)

**Comment by Z-fly** [comment]
Flet的问题？

**Comment by Bronya0** [comment]
mac适配了intel、m芯片，但是暂时没有适配mac_amd芯片，话说mac也有amd版本吗？恕我不太了解mac的情况

**Comment by Z-fly** [comment]
> mac适配了intel、m芯片，但是暂时没有适配mac_amd芯片，话说mac也有amd版本吗？恕我不太了解mac的情况

黑苹果啊。

**Comment by Bronya0** [comment]
> > mac适配了intel、m芯片，但是暂时没有适配mac_amd芯片，话说mac也有amd版本吗？恕我不太了解mac的情况
> 
> 黑苹果啊。

适配黑苹果amd太难了😂

**Comment by Bronya0** [comment]
> > mac适配了intel、m芯片，但是暂时没有适配mac_amd芯片，话说mac也有amd版本吗？恕我不太了解mac的情况
> 
> 黑苹果啊。

要不咱还是用windows吧

**Comment by Z-fly** [comment]
![image](https://github.com/Bronya0/ES-King/assets/10470892/6b64a5c8-051f-4f36-957f-1be23c7641ce)
是你的build.yml有问题

**Comment by Bronya0** [comment]
> ![image](https://private-user-images.githubusercontent.com/10470892/337536609-6b64a5c8-051f-4f36-957f-1be23c7641ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDE2NzQsIm5iZiI6MTcxNzc0MTM3NCwicGF0aCI6Ii8xMDQ3MDg5Mi8zMzc1MzY2MDktNmI2NGE1YzgtMDUxZi00ZjM2LTk1N2YtMWJlMjNjNzY0MWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA2MjI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1YjM4YTYyZGJjNThiNDQ3NTRkYTgxMTcxZjE1MDJiNjM1NGY1NDVjYjc2OTI2MjM3Nzk1NzY0MDViYjU4MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KcvwPc-AFno9e7IYVYE5OLNh8jD3gYyjVdlaEOjZg2Y) 是你的build.yml有问题

要不给build.yml提个pr吧😂
