### ISSUE TITLE
按钮放这儿不符合操作习惯，放右下角吧

### ISSUE THREAD

**Issue by bollowang** [Bronya0/ES-King#5]
<img width="2522" alt="image" src="https://github.com/Bronya0/ES-King/assets/22709567/bdd45ada-5806-48c0-8c3f-b3fa8f95bf1b">
按钮放这儿不符合操作习惯，改成放右下角吧

**Comment by Bronya0** [comment]
我也觉得，马上改

**Comment by Bronya0** [comment]
新版本已经改成点旁边自动退出对话框了，可以试用下：https://github.com/Bronya0/ES-King/releases/tag/v0.11
