### ISSUE TITLE
ES 集群开启用户名密码认证时，会报 401

### ISSUE THREAD

**Issue by SenreyS** [Bronya0/ES-King#6]
编辑链接时填写用户名密码后，点击测试链接会报 401，保存后选择连接会显示 401 Client Error：Unauthorized for url:http://xx.xx.xx.xx/_cluster/health

**Comment by Bronya0** [comment]
好的，回头看看

**Comment by Bronya0** [comment]
我修好重新给0.11版本打包了，你重新下载下看看 https://github.com/Bronya0/ES-King/releases/tag/v0.11

**Comment by SenreyS** [comment]
已经好了，感谢！辛苦了
